In [58]:
import numpy as np
import pandas as pd
import sys
import warnings
warnings.filterwarnings('ignore')

from sklearn.base import BaseEstimator
from sklearn.base import TransformerMixin
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

import problem

## Get Data

In [59]:
X, y = problem.get_train_data()
X_test, y_test = problem.get_test_data()

## Data preprocessing

In [60]:
from sklearn.impute import KNNImputer

# convert categorical columns to categorical type
cat_cols = [column_name for column_name in X.columns if str(
    X[column_name].dtype) == 'object']
num_cols = [
    column_name for column_name in X.columns if column_name not in cat_cols]
X[cat_cols] = X[cat_cols].astype('category')

In [61]:
# one hot encode to be able to use KNNImputation
X = pd.get_dummies(X, dummy_na=True)
for col in cat_cols:
    X.loc[X[col + "_nan"] == 1, X.columns.str.startswith(col)] = np.nan
    del X[col + "_nan"]

In [16]:
# impute values
imputer = KNNImputer(n_neighbors=5)
X = pd.DataFrame(imputer.fit_transform(X.values),columns = X.columns)

# revert dummification
for col in cat_cols:
    X[col] = X.loc[:, X.columns.str.startswith(col)].idxmax(axis=1).str.replace(col + "_", '')
    X = X.loc[:,~X.columns.str.startswith(col + "_")] 

# reset categorical column types
X[cat_cols] = X[cat_cols].astype('category')

In [17]:
X.head()

,age,duration,campaign,pdays,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,...,day_of_week_fri,day_of_week_mon,day_of_week_thu,day_of_week_tue,day_of_week_wed,day_of_week_nan,poutcome_failure,poutcome_nonexistent,poutcome_success,poutcome_nan
0,54.0,270.0,1.0,999.0,0.0,1.1,93.994,-36.4,4.864,5191.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,40.0,172.0,1.0,999.0,0.0,1.4,93.444,-36.1,4.963,5228.1,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
2,33.0,1060.0,2.0,999.0,0.0,1.4,93.918,-42.7,4.963,5228.1,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,33.0,165.0,1.0,999.0,1.0,-1.8,92.893,-46.2,1.291,5099.1,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
4,55.0,452.0,2.0,999.0,0.0,1.1,93.994,-36.4,4.857,5191.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0

dÃ©finir un workflow
faire un modÃ¨le
implÃ©menter une mÃ©trique qui prend en compte
l'imbalance